In [1]:
import numpy as np
import matplotlib.pyplot as pp

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
a.dtype

dtype('int32')

In [4]:
a = np.array([1,2,3,4,5],dtype=np.float64)
a

array([1., 2., 3., 4., 5.])

In [5]:
a.ndim, a.shape, a.size

(1, (5,), 5)

In [6]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float64)

In [7]:
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [8]:
b.dtype

dtype('float64')

In [9]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

In [10]:
np.zeros((3,3),'d')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.empty((4,4),'d')

array([[3.56043053e-307, 1.60219306e-306, 2.44763557e-307,
        1.69119330e-306],
       [1.33514617e-307, 2.55899112e-307, 1.24611130e-306,
        1.37959400e-306],
       [9.34604358e-307, 1.42419938e-306, 2.22518658e-306,
        1.24610383e-306],
       [1.78020169e-306, 1.78020984e-306, 8.34454050e-308,
        2.29179042e-312]])

In [13]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.random.standard_normal((2,4))

array([[ 0.01268484,  0.05120991, -1.90303414,  0.95709613],
       [-0.64675846, -1.26095064,  0.83129263,  1.26911399]])

In [16]:
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))

np.vstack([a,b])

array([[ 1.41790087,  0.30640344,  0.16035378],
       [ 1.30032621, -0.36264274,  0.29945088],
       [-0.49960705, -0.20259241,  0.31682465],
       [-0.46534519, -0.10518825,  0.25442795]])

In [16]:
np.hstack([a,b])

array([[ 1.26328274, -1.90693522,  0.00379105, -1.66929909,  0.82002641,
        -0.45799134],
       [-0.37768188, -0.34070629, -1.31688553, -0.03446812,  0.11392679,
         2.6503177 ]])

In [17]:
a.transpose()

array([[ 1.41790087,  1.30032621],
       [ 0.30640344, -0.36264274],
       [ 0.16035378,  0.29945088]])

In [18]:
np.save('example.npy',a)

In [19]:
a1 = np.load('example.npy')

In [20]:
a1

array([[ 1.41790087,  0.30640344,  0.16035378],
       [ 1.30032621, -0.36264274,  0.29945088]])